name: Jira Numbers Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Bash
      run: |
        jira_lynx_url="http://myurl"

        getJiraNumbers() {
          currentTag=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)
          previousTag=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "No previous tag")
          jiraNumbers=$(getGitCommits "$previousTag" "$currentTag")
          echo "$jiraNumbers"
        }

        getGitCommits() {
          previousTag="$1"
          currentTag="$2"
          echo "Previous tag: $previousTag"
          echo "Current tag: $currentTag"
          if [[ $currentTag == *Release* ]]; then
            echo 'Getting commits for a RELEASE branch'
            git fetch
            commits=$(git log --pretty=%s "$previousTag..$currentTag" --grep='Pull request')
          else
            echo 'Getting commits for a feature branch'
            commits=$(git log --pretty=%s "$previousTag..$currentTag")
          fi
          jiraNumbers=($(echo "$commits" | grep -o -E 'MED-[0-9]+' | sort -u))
          if [ ${#jiraNumbers[@]} -gt 0 ]; then
            echo "*** There are total ${#jiraNumbers[@]} commits found ***"
            for jira in "${jiraNumbers[@]}"; do
              createJiraLink "$jira"
            done
          else
            echo 'No Jira numbers were found in the commits'
          fi
        }

        createJiraLink() {
          storyNumber="$1"
          contextURL="$jira_lynx_url"
          jiraLink="[${storyNumber}](${contextURL}/${storyNumber})"
          echo "$jiraLink"
        }

        getJiraNumbers > jira_numbers.txt
      shell: bash

    - name: Display Jira Numbers
      run: cat jira_numbers.txt