name: Jira Numbers Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Bash
      run: |
        #!/bin/bash

        # Fetch tags from the remote repository
        git fetch --tags

        # Get the list of tags sorted by commit date and extract the latest tag
        currentTag=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)

        # Get the previous tag based on the current tag
        previousTag=$(git describe --tags --abbrev=0 $currentTag^ 2>/dev/null || echo "No previous tag")

        # Output the current and previous tags
        echo "Current tag: $currentTag"
        echo "Previous tag: $previousTag"

        # Print all the commits between current and previous tags
        git log $previousTag..$currentTag --oneline > jira_numbers.txt
        
      shell: bash

    - name: Display Jira Numbers
      run: cat jira_numbers.txt